// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/activity-log": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns paginated activity logs enriched with source/shadow scope from V2 metadata. Supports source/shadow filters while keeping target_table as compatibility fallback.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity Log"
                ],
                "summary": "List activity logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Operation filter",
                        "name": "operation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Status filter",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Triggered by filter",
                        "name": "triggered_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Legacy target_table filter",
                        "name": "target_table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Source database filter",
                        "name": "source_database",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Source table filter",
                        "name": "source_table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Shadow schema filter",
                        "name": "shadow_schema",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Shadow table filter",
                        "name": "shadow_table",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/activity-log/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns 24h aggregated activity stats and recent errors enriched with V2 source/shadow scope.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Activity Log"
                ],
                "summary": "Get activity log stats",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/jobs/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the cdc_system.cdc_jobs row written by the CommandBus on Dispatch and updated by the worker JobMonitor on cdc.evt.X.completed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jobs"
                ],
                "summary": "Get async job",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapping-rules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns V2 mapping rules, optionally filtered by source object or source/shadow scope. Legacy table/source_table params are still accepted as fallback.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "List mapping rules",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by source object ID",
                        "name": "source_object_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_database",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source object name",
                        "name": "source_table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by shadow schema",
                        "name": "shadow_schema",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by shadow table",
                        "name": "shadow_table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a V2 mapping rule in cdc_system.mapping_rule_v2. Supports source_object_id or source/shadow scope resolution; legacy source_table is accepted as fallback.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "Create a mapping rule",
                "parameters": [
                    {
                        "description": "Mapping rule details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_api_dto.MappingRuleCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapping-rules/reload": {
            "post": {
                "description": "Publishes a NATS message to trigger workers to reload mapping rules from DB.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "Reload mapping rules for workers",
                "responses": {}
            }
        },
        "/api/mapping-rules/{id}": {
            "patch": {
                "description": "Updates the status of a V2 mapping rule.",
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "Update mapping rule status",
                "responses": {}
            }
        },
        "/api/schema-changes/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns audit log of all schema changes (ALTER TABLE, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "Get schema change history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by table name",
                        "name": "table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/schema-changes/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns pending fields detected by Schema Inspector, with pagination and filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "List pending schema changes",
                "parameters": [
                    {
                        "enum": [
                            "pending",
                            "approved",
                            "rejected"
                        ],
                        "type": "string",
                        "default": "pending",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_db",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by table name",
                        "name": "table",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/schema-changes/{id}/approve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Approves a pending field: ALTER TABLE ADD COLUMN, create mapping rule, publish config reload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "Approve a schema change",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pending field ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Approval details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_infra_persistence.ApproveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/schema-changes/{id}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rejects a pending field with a reason",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "Reject a schema change",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pending field ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rejection reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_infra_persistence.RejectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/cms/sources/{id}/provisioning": {
            "get": {
                "tags": [
                    "Provisioning"
                ],
                "summary": "Snapshot of provisioning state for one source",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "source_object_registry.id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_infra_persistence.SourceProvisioningSnapshot"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/masters": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns V2 master bindings enriched with source and shadow metadata from cdc_system.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Masters"
                ],
                "summary": "List master bindings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/masters/{name}/swap": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Kicks off an atomic master-table swap as a background job. Returns 202 + JobID; poll GET /api/jobs/:id for terminal status. Refuses with 409 if another swap for the same master is still in flight.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Masters"
                ],
                "summary": "Swap physical master tables (async)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Master table name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Swap payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.SwapRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/shadow-bindings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns active and inactive shadow bindings from cdc_system.shadow_binding enriched with source-object metadata and latest reconciliation context.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "List V2 shadow bindings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_db",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "Filter by active status",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.shadowBindingsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns source objects from cdc_system.source_object_registry enriched with active shadow binding, reconciliation status, and transitional registry bridge metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "List V2 source objects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_db",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "Filter by active status",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.sourceObjectsListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/registry/{registry_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns a single source-object mapping context resolved from the current registry bridge, enriched with V2 source/shadow metadata for the mapping page.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Get mapping context by legacy registry bridge",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Legacy registry bridge ID",
                        "name": "registry_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.SourceObjectMappingContext"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns summary stats from cdc_system source objects enriched with transitional priority and shadow-DDL creation state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Get V2 source-object statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.SourceObjectStats"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates source-object metadata directly in cdc_system for rows that no longer rely on the legacy registry bridge. Supported fields: is_active, timestamp_field, notes.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Update a V2 source object directly",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Source object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/{id}/create-default-columns": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Dispatches create-default-columns using source_object_id and the active shadow binding. The worker receives schema-aware payload so post-create state can be reflected back into V2 metadata.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Create default columns for a V2 source object",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Source object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/{id}/detect-timestamp-field": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Dispatches timestamp-field auto-detection using source_object_id and the active shadow binding instead of the legacy registry bridge. The worker still consumes the existing NATS subject and resolves by target_table fallback.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Re-detect timestamp field for a V2 source object",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Source object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/{id}/dispatch-status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reads activity-log based dispatch status for direct V2 source-object actions such as timestamp re-detection, using source_object_id to resolve the current shadow target.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Get dispatch status for a V2 source-object action",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Source object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Operation filter, e.g. detect-timestamp-field",
                        "name": "subject",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339 timestamp lower bound",
                        "name": "since",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/{id}/scan-fields": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Dispatches scan-fields using source_object_id and the active shadow binding instead of the legacy registry bridge. Worker payload stays compatible with the current Debezium-only scan path.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Scan fields for a V2 source object",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Source object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/{id}/standardize": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Dispatches standardize using source_object_id and the active shadow binding instead of the legacy registry bridge. Worker payload remains compatible because standardize only requires the resolved target table.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Standardize a V2 source object",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Source object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/source-objects/{id}/transform-status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Resolves the active shadow target for a source object and returns transform progress without requiring the legacy registry bridge.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Source Objects"
                ],
                "summary": "Get transform progress for a V2 source object",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Source object ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/worker-schedule": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns operator-flow schedules with enriched source/shadow scope from V2 metadata when available.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "List worker schedules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates an operator-flow schedule override. Accepts legacy target_table and can also resolve richer source/shadow scope against V2 metadata.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Create worker schedule",
                "parameters": [
                    {
                        "description": "Schedule create payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.WorkerScheduleCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/worker-schedule/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates interval, enabled state, or notes for an existing operator-flow schedule.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Operations"
                ],
                "summary": "Update worker schedule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Schedule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Schedule update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.WorkerScheduleUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns service readiness (checks DB connection)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cdc-cms-service_internal_api_dto.MappingRuleCreateRequest": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_nullable": {
                    "type": "boolean"
                },
                "master_binding_id": {
                    "type": "integer"
                },
                "notes": {
                    "type": "string"
                },
                "shadow_schema": {
                    "type": "string"
                },
                "shadow_table": {
                    "type": "string"
                },
                "source_database": {
                    "type": "string"
                },
                "source_field": {
                    "type": "string"
                },
                "source_format": {
                    "type": "string"
                },
                "source_namespace": {
                    "type": "string"
                },
                "source_object_id": {
                    "type": "integer"
                },
                "source_path": {
                    "type": "string"
                },
                "source_schema": {
                    "type": "string"
                },
                "source_table": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "target_column": {
                    "type": "string"
                },
                "transform_fn": {
                    "type": "string"
                }
            }
        },
        "cdc-cms-service_internal_infra_persistence.ApproveRequest": {
            "type": "object",
            "properties": {
                "approval_notes": {
                    "type": "string",
                    "example": "Approved for phase 1"
                },
                "final_type": {
                    "type": "string",
                    "example": "INTEGER"
                },
                "target_column_name": {
                    "type": "string",
                    "example": "loyalty_points"
                }
            }
        },
        "cdc-cms-service_internal_infra_persistence.RejectRequest": {
            "type": "object",
            "properties": {
                "rejection_reason": {
                    "type": "string",
                    "example": "Not needed for MVP"
                }
            }
        },
        "cdc-cms-service_internal_infra_persistence.SourceProvisioningSnapshot": {
            "type": "object",
            "properties": {
                "last_step_error": {
                    "type": "string"
                },
                "provisioning_mode": {
                    "type": "string"
                },
                "provisioning_state": {
                    "type": "string"
                },
                "provisioning_step_log": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "source_id": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_api.ShadowBindingRow": {
            "type": "object",
            "properties": {
                "binding_code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "ddl_status": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "last_recon_at": {
                    "type": "string"
                },
                "object_code": {
                    "type": "string"
                },
                "physical_table_fqn": {
                    "type": "string"
                },
                "recon_drift": {
                    "type": "integer"
                },
                "registry_id": {
                    "type": "integer"
                },
                "shadow_schema": {
                    "type": "string"
                },
                "shadow_table": {
                    "type": "string"
                },
                "source_db": {
                    "type": "string"
                },
                "source_object_id": {
                    "type": "integer"
                },
                "source_table": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "write_mode": {
                    "type": "string"
                }
            }
        },
        "internal_api.SourceObjectMappingContext": {
            "type": "object",
            "properties": {
                "bridge_status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "ddl_status": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_table_created": {
                    "type": "boolean"
                },
                "metadata_status": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "object_code": {
                    "type": "string"
                },
                "physical_table_fqn": {
                    "type": "string"
                },
                "primary_key_field": {
                    "type": "string"
                },
                "primary_key_type": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "profile_status": {
                    "type": "string"
                },
                "recon_drift": {
                    "type": "integer"
                },
                "registry_id": {
                    "type": "integer"
                },
                "shadow_binding_id": {
                    "type": "integer"
                },
                "shadow_schema": {
                    "type": "string"
                },
                "source_db": {
                    "type": "string"
                },
                "source_table": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "sync_engine": {
                    "type": "string"
                },
                "sync_interval": {
                    "type": "string"
                },
                "sync_status": {
                    "type": "string"
                },
                "target_table": {
                    "type": "string"
                },
                "timestamp_field": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_api.SourceObjectRow": {
            "type": "object",
            "properties": {
                "bridge_status": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "ddl_status": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_table_created": {
                    "type": "boolean"
                },
                "metadata_status": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "object_code": {
                    "type": "string"
                },
                "physical_table_fqn": {
                    "type": "string"
                },
                "primary_key_field": {
                    "type": "string"
                },
                "primary_key_type": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "profile_status": {
                    "type": "string"
                },
                "provisioning_mode": {
                    "type": "string"
                },
                "provisioning_state": {
                    "type": "string"
                },
                "recon_drift": {
                    "type": "integer"
                },
                "registry_id": {
                    "type": "integer"
                },
                "shadow_binding_id": {
                    "type": "integer"
                },
                "shadow_schema": {
                    "type": "string"
                },
                "source_db": {
                    "type": "string"
                },
                "source_engine_type": {
                    "type": "string"
                },
                "source_table": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "sync_engine": {
                    "type": "string"
                },
                "sync_interval": {
                    "type": "string"
                },
                "sync_status": {
                    "type": "string"
                },
                "target_table": {
                    "type": "string"
                },
                "timestamp_field": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "internal_api.SourceObjectStats": {
            "type": "object",
            "properties": {
                "by_priority": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "by_source_db": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "by_sync_engine": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "tables_created": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_api.SwapRequest": {
            "type": "object",
            "properties": {
                "new_table_name": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "internal_api.WorkerScheduleCreateRequest": {
            "type": "object",
            "properties": {
                "interval_minutes": {
                    "type": "integer"
                },
                "is_enabled": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                },
                "shadow_schema": {
                    "type": "string"
                },
                "shadow_table": {
                    "type": "string"
                },
                "source_database": {
                    "type": "string"
                },
                "source_namespace": {
                    "type": "string"
                },
                "source_schema": {
                    "type": "string"
                },
                "source_table": {
                    "type": "string"
                },
                "target_table": {
                    "type": "string"
                }
            }
        },
        "internal_api.WorkerScheduleUpdateRequest": {
            "type": "object",
            "properties": {
                "interval_minutes": {
                    "type": "integer"
                },
                "is_enabled": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                }
            }
        },
        "internal_api.shadowBindingsListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.ShadowBindingRow"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_api.sourceObjectsListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_api.SourceObjectRow"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter \"Bearer {token}\" to authenticate",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CDC CMS Service API",
	Description:      "CMS Service for CDC Integration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
