// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/airbyte/import/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Imports selected streams from Airbyte into CMS Registry and creates default mapping rules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airbyte"
                ],
                "summary": "Execute smart import",
                "parameters": [
                    {
                        "description": "Import configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_api.ImportStream"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/airbyte/import/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Shows streams from Airbyte that are not yet in the CMS Registry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airbyte"
                ],
                "summary": "List importable streams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/api/airbyte/jobs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches the 20 most recent sync jobs from Airbyte",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airbyte"
                ],
                "summary": "List Airbyte Jobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cdc-cms-service_pkgs_airbyte.JobStatus"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/airbyte/sources": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetches all configured source connectors from Airbyte",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airbyte"
                ],
                "summary": "List Airbyte Sources",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cdc-cms-service_pkgs_airbyte.Source"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/airbyte/sync-audit": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Compares Airbyte connection state with CMS Registry to find inconsistencies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Airbyte"
                ],
                "summary": "Audit Sync State",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cdc-cms-service_pkgs_airbyte.StreamAudit"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/introspection/scan-raw/{table}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Directly scans the _raw_data column in the DW table to find fields not yet mapped. Works without Airbyte API.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Introspection"
                ],
                "summary": "Scan _raw_data JSONB for unmapped fields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target table name (e.g. cdc_merchants)",
                        "name": "table",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/introspection/scan/{table}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Scans the _raw_data column of a target table to find fields that are not yet mapped",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Introspection"
                ],
                "summary": "Scan raw data for new fields",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target table name",
                        "name": "table",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapping-rules": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all mapping rules, optionally filtered by table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "List mapping rules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source table",
                        "name": "table",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new field mapping rule and publishes config reload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "Create a mapping rule",
                "parameters": [
                    {
                        "description": "Mapping rule details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_model.MappingRule"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapping-rules/reload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Publishes a NATS message to trigger workers to reload mapping rules from DB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "Reload mapping rules for workers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Specific table to reload",
                        "name": "table",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapping-rules/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the status of a mapping rule (approve/reject)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "Update mapping rule status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mapping Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Status update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/mapping-rules/{id}/backfill": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Populates the target column with values from _raw_data for existing rows where target column is NULL",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mapping Rules"
                ],
                "summary": "Backfill data for a mapping rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mapping Rule ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns all registered CDC tables with pagination and filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "List table registry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_db",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "airbyte",
                            "debezium",
                            "both"
                        ],
                        "type": "string",
                        "description": "Filter by sync engine",
                        "name": "sync_engine",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "critical",
                            "high",
                            "normal",
                            "low"
                        ],
                        "type": "string",
                        "description": "Filter by priority",
                        "name": "priority",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "true",
                            "false"
                        ],
                        "type": "string",
                        "description": "Filter by active status",
                        "name": "is_active",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a new table in the registry and auto-creates the CDC table in PostgreSQL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Register a new CDC table",
                "parameters": [
                    {
                        "description": "Table registration details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_model.TableRegistry"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers multiple tables at once and creates their CDC tables",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Bulk register tables",
                "parameters": [
                    {
                        "description": "Array of table registrations",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cdc-cms-service_internal_model.TableRegistry"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/scan-source": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Discovers all streams in an Airbyte source and registers them in CDC registry if not exists (with is_active=false)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Scan Airbyte source for new tables",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airbyte Source ID",
                        "name": "source_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns summary stats: total tables, by source_db, by sync_engine, by priority",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Get registry statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_repository.RegistryStats"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates sync_engine, sync_interval, priority, or is_active for a registered table",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Update table registry entry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}/discover": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Scans database columns and populates cdc_mapping_rules for the table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Discover field mappings from database",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}/jobs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the 10 most recent sync jobs for the connection associated with this table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Get recent Airbyte sync jobs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/cdc-cms-service_pkgs_airbyte.JobStatus"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}/refresh-catalog": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Triggers Airbyte schema discovery to re-add missing streams back to the connection catalog.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Refresh Airbyte source schema catalog",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}/scan-fields": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Uses Airbyte Discovery API to find new fields and register them as 'pending' in mapping rules",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Scan source fields for a registered table",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}/standardize": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds missing metadata columns (_raw_data, _source, etc.) to an existing table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Standardize table metadata columns",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the current sync status from Airbyte for a registered table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Get Airbyte sync status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/registry/{id}/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Triggers a manual sync job in Airbyte for the connection associated with this table",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Table Registry"
                ],
                "summary": "Force Airbyte sync",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Registry entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/schema-changes/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns audit log of all schema changes (ALTER TABLE, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "Get schema change history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by table name",
                        "name": "table",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/schema-changes/pending": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns pending fields detected by Schema Inspector, with pagination and filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "List pending schema changes",
                "parameters": [
                    {
                        "enum": [
                            "pending",
                            "approved",
                            "rejected"
                        ],
                        "type": "string",
                        "default": "pending",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source database",
                        "name": "source_db",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by table name",
                        "name": "table",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/schema-changes/{id}/approve": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Approves a pending field: ALTER TABLE ADD COLUMN, create mapping rule, publish config reload",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "Approve a schema change",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pending field ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Approval details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_service.ApproveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/schema-changes/{id}/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Rejects a pending field with a reason",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Schema Changes"
                ],
                "summary": "Reject a schema change",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Pending field ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Rejection reason",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/cdc-cms-service_internal_service.RejectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "Returns service readiness (checks DB connection)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cdc-cms-service_internal_model.MappingRule": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "data_type": {
                    "type": "string"
                },
                "default_value": {
                    "type": "string"
                },
                "enrichment_function": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_enriched": {
                    "type": "boolean"
                },
                "is_nullable": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "rule_type": {
                    "description": "Phase 1.10: rule_type — system | discovered | mapping",
                    "type": "string"
                },
                "source_field": {
                    "type": "string"
                },
                "source_table": {
                    "type": "string"
                },
                "status": {
                    "description": "Phase 1.10: Status workflow — pending | approved | rejected",
                    "type": "string"
                },
                "target_column": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "updated_by": {
                    "type": "string"
                }
            }
        },
        "cdc-cms-service_internal_model.TableRegistry": {
            "type": "object",
            "properties": {
                "airbyte_connection_id": {
                    "type": "string"
                },
                "airbyte_cursor_field": {
                    "type": "string"
                },
                "airbyte_destination_id": {
                    "type": "string"
                },
                "airbyte_destination_name": {
                    "type": "string"
                },
                "airbyte_destination_sync_mode": {
                    "type": "string"
                },
                "airbyte_namespace": {
                    "type": "string"
                },
                "airbyte_raw_table": {
                    "type": "string"
                },
                "airbyte_source_id": {
                    "type": "string"
                },
                "airbyte_sync_mode": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_partitioned": {
                    "type": "boolean"
                },
                "is_table_created": {
                    "type": "boolean"
                },
                "last_bridge_at": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "partition_key": {
                    "type": "string"
                },
                "primary_key_field": {
                    "type": "string"
                },
                "primary_key_type": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "source_db": {
                    "type": "string"
                },
                "source_table": {
                    "type": "string"
                },
                "source_type": {
                    "type": "string"
                },
                "sync_engine": {
                    "type": "string"
                },
                "sync_interval": {
                    "type": "string"
                },
                "target_table": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "cdc-cms-service_internal_repository.RegistryStats": {
            "type": "object",
            "properties": {
                "by_priority": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "by_source_db": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "by_sync_engine": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                },
                "tables_created": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "cdc-cms-service_internal_service.ApproveRequest": {
            "type": "object",
            "properties": {
                "approval_notes": {
                    "type": "string",
                    "example": "Approved for phase 1"
                },
                "final_type": {
                    "type": "string",
                    "example": "INTEGER"
                },
                "target_column_name": {
                    "type": "string",
                    "example": "loyalty_points"
                }
            }
        },
        "cdc-cms-service_internal_service.RejectRequest": {
            "type": "object",
            "properties": {
                "rejection_reason": {
                    "type": "string",
                    "example": "Not needed for MVP"
                }
            }
        },
        "cdc-cms-service_pkgs_airbyte.JobStatus": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "jobId": {
                    "type": "integer"
                },
                "status": {
                    "description": "E.g., \"running\", \"succeeded\", \"failed\"",
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "cdc-cms-service_pkgs_airbyte.MismatchType": {
            "type": "string",
            "enum": [
                "status_mismatch",
                "missing_stream",
                "orphan_stream"
            ],
            "x-enum-comments": {
                "MismatchMissing": "e.g. Table in CMS but NOT in Airbyte connection",
                "MismatchOrphan": "e.g. Stream selected in Airbyte but NOT in CMS Registry",
                "MismatchStatus": "e.g. CMS active, Airbyte selected = false"
            },
            "x-enum-descriptions": [
                "e.g. CMS active, Airbyte selected = false",
                "e.g. Table in CMS but NOT in Airbyte connection",
                "e.g. Stream selected in Airbyte but NOT in CMS Registry"
            ],
            "x-enum-varnames": [
                "MismatchStatus",
                "MismatchMissing",
                "MismatchOrphan"
            ]
        },
        "cdc-cms-service_pkgs_airbyte.Source": {
            "type": "object",
            "properties": {
                "connectionId": {
                    "type": "string"
                },
                "database": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sourceId": {
                    "type": "string"
                },
                "sourceName": {
                    "type": "string"
                },
                "workspaceId": {
                    "type": "string"
                }
            }
        },
        "cdc-cms-service_pkgs_airbyte.StreamAudit": {
            "type": "object",
            "properties": {
                "airbyte_selected": {
                    "type": "boolean"
                },
                "mismatch_type": {
                    "$ref": "#/definitions/cdc-cms-service_pkgs_airbyte.MismatchType"
                },
                "stream_name": {
                    "type": "string"
                },
                "system_active": {
                    "type": "boolean"
                },
                "table_name": {
                    "type": "string"
                }
            }
        },
        "internal_api.ImportStream": {
            "type": "object",
            "properties": {
                "connection_id": {
                    "type": "string"
                },
                "stream_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter \"Bearer {token}\" to authenticate",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CDC CMS Service API",
	Description:      "CMS Service for CDC Integration - Schema change approval, table registry, mapping rules management.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
