server:
  name: cdc-auth-service
  port: ":8081"
  mode: dev

db:
  host: localhost
  port: 5432
  username: gpay_admin
  password: gpay_pass
  database: gpay_auth
  sslMode: disable
  maxOpenConn: 10
  maxIdleConn: 5
  connMaxLifetime: 5m

jwt:
  secret: change-me-in-production
  accessExpiration: 24h
  refreshExpiration: 168h
