// Package docs Code generated by swaggo/swag. DO NOT EDIT
//
// Swagger regen pending post-Sprint 4 cleanup. The full endpoint spec is
// intentionally stubbed here until `swag init` is re-run by an operator
// with the swag CLI installed. Runtime Swagger UI will serve a minimal
// landing page showing only the retired-state info; real API discovery
// happens via source-level `@Summary` annotations in internal/api/*.go.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "CDC CMS Service API",
	Description:      "CMS Service for CDC Integration — Debezium-native pipeline (Sprint 4). Re-run `swag init` after annotation changes to populate paths.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
